// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhoUnfollows;

namespace WhoUnfollows.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("InstagramApiSharp.Classes.Models.InstaUserShort", b =>
                {
                    b.Property<long>("Pk")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.Property<bool>("IsPrivate");

                    b.Property<bool>("IsVerified");

                    b.Property<string>("ProfilePicUrl");

                    b.Property<string>("ProfilePicture");

                    b.Property<string>("ProfilePictureId");

                    b.Property<string>("UserName");

                    b.HasKey("Pk");

                    b.ToTable("InstaUserShort");
                });
#pragma warning restore 612, 618
        }
    }
}
