#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WhoUnfollows.Resource", IsApplication=true)]

namespace WhoUnfollows
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int accent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int primary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int primaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int splash_background = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int window_background = 2130771972;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int logo = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int logo2 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int splash_logo = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int splash_screen = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int AnaSayfa = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Buttonn = 2130903041;
			
			// aapt resource value: 0x7F030007
			public const int hakkindaSayfasi = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int hayranlarSayfasi = 2130903048;
			
			// aapt resource value: 0x7F030002
			public const int Image = 2130903042;
			
			// aapt resource value: 0x7F030009
			public const int imageLogo = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int imageView1 = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int kullaniciAdi = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int listView1 = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int listView2 = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int logOut = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int myButton = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int progressBar1 = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int progressBar2 = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int reflesh = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int takipciler = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int takipcilerSayfasi = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int takipedilenler = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int tbEmail = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int tbPassword = 2130903063;
			
			// aapt resource value: 0x7F030003
			public const int Text = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int Text1 = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int Text2 = 2130903045;
			
			// aapt resource value: 0x7F030018
			public const int textView1 = 2130903064;
			
			// aapt resource value: 0x7F030006
			public const int Yukleme = 2130903046;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Menu = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int takipciler = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int UnFollowers = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int Icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int logo1 = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int logout = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int hello = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
